export enum RouteNames {
    SEPARATOR = '/',

    PUBLIC_BUILDING = '/building',
    PUBLIC_BUILDING_ITEM = '/building/:id',
    PUBLIC_RENT = '/rent',
    PUBLIC_RENT_ITEM = '/rent/:id',
    PUBLIC_ARTICLE = '/article',
    PUBLIC_ARTICLE_ITEM = '/article/:id',
    PUBLIC_POLICY = '/policy',
    PUBLIC_ABOUT = '/about',
    PUBLIC_FAQ = '/faq',

    SUPPORT = '/panel/support',


    MAIN = '/',
    USER = '/panel/user',
    USER_ITEM = '/panel/user/:id',
    BUILDING = '/panel/building',
    BUILDING_ITEM = '/panel/building/:id',
    ARTICLE = '/panel/article',
    ARTICLE_ITEM = '/panel/article/:id',
    DOCUMENT = '/panel/document',
    REPORT = '/panel/report',
    TOOL = '/panel/tool',
    FAVORITE = '/panel/favorite',
    FILE_MANAGER = '/panel/file-manager',
    ADMINISTRATION = '/panel/administration',
    TARIFF = '/panel/tariff',
    ADVERTISING = '/panel/advertising',
    ADVERTISING_PARTNER = '/panel/advertising/partner',
    ADVERTISING_PARTNER_ITEM = '/panel/advertising/partner/:id',
    ADVERTISING_BANNER = '/panel/advertising/banner',
    ADVERTISING_WIDGET = '/panel/advertising/widget',
    ADVERTISING_FAQ = '/panel/advertising/faq',
    CRM = '/panel/crm',
    CRM_DEVELOPER = '/panel/crm/developer',
    CRM_DEVELOPER_ITEM = '/panel/crm/developer/:id',
    CRM_AGENT = '/panel/crm/agent',
    CRM_AGENT_ITEM = '/panel/crm/agent/:id',
    CRM_POST = '/panel/crm/post',
    CRM_BP = '/panel/crm/bp',
    CRM_BOOKING = '/panel/crm/booking',
    CRM_PAYMENT = '/panel/crm/payment',
    CRM_USER_EXTERNAL = '/panel/crm/user-external',
    CRM_COMPILATION = '/panel/compilation',
    CRM_COMPILATION_ITEM = '/panel/compilation/:id',
    CRM_MAILING = '/panel/crm/mailing',
    PUBLIC_PARTNER_ITEM = '/partner/:id'
}