export enum RouteNames {
    MAIN = '/',
    USER = '/panel/user',
    USER_ITEM = '/panel/user/:id',
    BUILDING = '/panel/building',
    BUILDING_ITEM = '/panel/building/:id',
    ARTICLE = '/panel/article',
    ARTICLE_ITEM = '/panel/article/:id',
    DEVELOPER = '/panel/developer',
    DOCUMENT = '/panel/document',
    REPORT = '/panel/report',
    TOOL = '/panel/tool',
    SUPPORT = '/panel/support',
    FAVORITE = '/panel/favorite',
    COMPILATION = '/panel/compilation',
    PROFILE = '/panel/profile',
    PUBLIC_BUILDING = '/building',
    PUBLIC_BUILDING_ITEM = '/building/:id',
    PUBLIC_ARTICLE = '/article',
    PUBLIC_ARTICLE_ITEM = '/article/:id',
    PUBLIC_POLICY = '/policy',
    PUBLIC_ABOUT = '/about'
}