export enum RouteNames {
    SEPARATOR = '/',

    MAIN = '/',
    PUBLIC_BUILDING = '/building',
    PUBLIC_BUILDING_ITEM = '/building/:id',
    PUBLIC_RENT = '/rent',
    PUBLIC_RENT_ITEM = '/rent/:id',
    PUBLIC_ARTICLE = '/article',
    PUBLIC_ARTICLE_ITEM = '/article/:id',
    PUBLIC_POLICY = '/policy',
    PUBLIC_ABOUT = '/about',
    PUBLIC_FAQ = '/faq',

    P_DESKTOP = '/desktop',
    P_USER = '/user',
    P_BUILDING = '/panel/building',
    P_ARTICLE = '/panel/article',
    P_DOCUMENT = '/panel/document',
    P_FILE_MANAGER = '/panel/file-manager',
    P_CATALOG = '/catalog',
    P_CRM = '/crm',
    P_REPORT = '/report',
    P_TOOL = '/tool',
    P_ADMINISTRATION = '/administration',
    P_SUPPORT = '/support',
    P_BP = '/panel/crm/bp',
    P_COMPILATION = '/panel/compilation',
    P_AGENT = '/panel/crm/agent',
    P_DEVELOPER = '/panel/crm/developer',
    P_POST = '/panel/crm/post',
    P_BOOKING = '/panel/crm/booking',
    P_PAYMENT = '/panel/crm/payment',
    P_MAILING = '/panel/crm/mailing',
    P_USER_EXTERNAL = '/panel/crm/user-external',
    P_QUESTION = '/question',


    P_PARTNER = '/panel/advertising/partner',
    P_BANNER = '/panel/advertising/banner',
    P_WIDGET = '/panel/advertising/widget',

    USER_ITEM = '/panel/user/:id',
    BUILDING_ITEM = '/panel/building/:id',
    ARTICLE_ITEM = '/panel/article/:id',
    FAVORITE = '/panel/favorite',
    TARIFF = '/panel/tariff',
    ADVERTISING = '/panel/advertising',
    ADVERTISING_PARTNER_ITEM = '/panel/advertising/partner/:id',
    ADVERTISING_FAQ = '/panel/advertising/faq',
    CRM_DEVELOPER_ITEM = '/panel/crm/developer/:id',
    CRM_AGENT_ITEM = '/panel/crm/agent/:id',
    CRM_COMPILATION_ITEM = '/panel/compilation/:id',
    PUBLIC_PARTNER_ITEM = '/partner/:id'
}