export enum RouteNames {
    SEPARATOR = '/',

    MAIN = '/',
    ABOUT = '/about',
    POLICY = '/policy',
    FAQ = '/faq',
    ARTICLE = '/article',
    ARTICLE_ITEM = '/article/:id',
    BUILDING = '/building',
    BUILDING_ITEM = '/building/:id',
    RENT = '/rent',
    RENT_ITEM = '/rent/:id',

    P_DESKTOP = '/desktop',
    P_USER = '/user',
    P_BUILDING = '/panel/building',
    P_ARTICLE = '/panel/article',
    P_DOCUMENT = '/document',
    P_FILE_MANAGER = '/file-manager',
    P_CATALOG = '/catalog',
    P_CRM = '/crm',
    P_QUESTION = '/question',
    P_REPORT = '/report',
    P_TOOL = '/tool',
    P_ADMINISTRATION = '/administration',
    P_SUPPORT = '/support',
    P_BP = '/bp',
    P_COMPILATION = '/compilation',
    P_AGENT = '/agent',
    P_DEVELOPER = '/developer',
    P_POST = '/post',
    P_BOOKING = '/booking',
    P_PAYMENT = '/payment',
    P_MAILING = '/mailing',
    P_USER_EXTERNAL = '/user-external',



    P_PARTNER = '/panel/advertising/partner',
    P_BANNER = '/panel/advertising/banner',
    P_WIDGET = '/panel/advertising/widget',

    USER_ITEM = '/panel/user/:id',
    // BUILDING = '/panel/building',
    // BUILDING_ITEM = '/panel/building/:id',
    // ARTICLE = '/panel/article',
    // ARTICLE_ITEM = '/panel/article/:id',
    FAVORITE = '/panel/favorite',
    COMPILATION_ITEM = '/panel/compilation/:id',
    TARIFF = '/panel/tariff',
    ADVERTISING_PARTNER_ITEM = '/panel/advertising/partner/:id',
    CRM_DEVELOPER_ITEM = '/panel/crm/developer/:id',
    PUBLIC_PARTNER_ITEM = '/partner/:id'
}