export enum RouteNames {
    MAIN = '/',
    ABOUT = '/about',
    POLICY = '/policy',
    FAQ = '/faq',
    ARTICLE = '/article',
    ARTICLE_ITEM = '/article/:id',
    BUILDING = '/building',
    BUILDING_ITEM = '/building/:id',
    RENT = '/rent',
    RENT_ITEM = '/rent/:id',
    P_SUPPORT = '/support',



    USER = '/panel/user',
    USER_ITEM = '/panel/user/:id',
    // BUILDING = '/panel/building',
    // BUILDING_ITEM = '/panel/building/:id',
    // ARTICLE = '/panel/article',
    // ARTICLE_ITEM = '/panel/article/:id',
    DOCUMENT = '/panel/document',
    REPORT = '/panel/report',
    TOOL = '/panel/tool',
    FAVORITE = '/panel/favorite',
    COMPILATION = '/panel/compilation',
    COMPILATION_ITEM = '/panel/compilation/:id',
    FILE_MANAGER = '/panel/file-manager',
    ADMINISTRATION = '/panel/administration',
    TARIFF = '/panel/tariff',
    ADVERTISING = '/panel/advertising',
    ADVERTISING_PARTNER = '/panel/advertising/partner',
    ADVERTISING_PARTNER_ITEM = '/panel/advertising/partner/:id',
    ADVERTISING_BANNER = '/panel/advertising/banner',
    ADVERTISING_WIDGET = '/panel/advertising/widget',
    ADVERTISING_FAQ = '/panel/advertising/faq',
    CRM = '/panel/crm',
    CRM_DEVELOPER = '/panel/crm/developer',
    CRM_DEVELOPER_ITEM = '/panel/crm/developer/:id',
    CRM_POST = '/panel/crm/post',
    CRM_BP = '/panel/crm/bp',
    CRM_BOOKING = '/panel/crm/booking',
    CRM_PAYMENT = '/panel/crm/payment',
    CRM_USER_EXTERNAL = '/panel/crm/user-external',
    PUBLIC_PARTNER_ITEM = '/partner/:id'
}